<a href="https://colab.research.google.com/github/RohitMangale/ML/blob/main/pythonLibraries/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy Basics_Array
import numpy as np

In [ ]:
import numpy as np

# np.array(object, dtype=None, copy=True, order='K', subdtype=None, ndmin=0)
# Definition: Creates a NumPy array from a Python sequence.
a = np.array([1, 2, 3])
print(a)
#Converts various data structures (lists, tuples, etc.) into NumPy arrays.

# np.arange(start, stop=None, step=1, dtype=None)
# Definition: Creates an array with evenly spaced values within a given interval.
a = np.arange(10)
print(a)
# Generates a sequence of numbers with a specified step size.

# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# Definition: Creates an array with evenly spaced numbers over a specified interval.
a = np.linspace(0, 1, 5)
print(a)
# Generates a specified number of evenly spaced values between a start and stop value.

# np.zeros(shape, dtype=float, order='C')
# Definition: Creates an array filled with zeros.
a = np.zeros((3, 4))
print(a)
# Creates an array of specified shape with all elements initialized to zero.

# np.ones(shape, dtype=float, order='C')
# Definition: Creates an array filled with ones.
a = np.ones((2, 2))
print(a)
# Creates an array of specified shape with all elements initialized to one.

# np.empty(shape, dtype=float, order='C')
# Definition: Creates an array without initializing its values.
a = np.empty((2, 3))
print(a)
# Creates an array of specified shape but with uninitialized values.

# np.full(shape, fill_value, dtype=None, order='C')
# Definition: Creates an array filled with a specified value.
a = np.full((2, 2), 7)
print(a)
# Creates an array of specified shape with all elements filled with a given value.

# np.eye(N, M=None, k=0, dtype=<class 'float64'>)
# Definition: Creates an identity matrix.
a = np.eye(3)
print(a)
# Creates a square matrix with ones on the main diagonal and zeros elsewhere.

# arr.shape
# Definition: Returns the shape of the array.
shape = a.shape
print(shape)
# Provides the dimensions of the array as a tuple.

# arr.ndim
# Definition: Returns the number of dimensions of the array.
ndim = a.ndim
print(ndim)
# Gives the rank or dimensionality of the array.

# arr.size
# Definition: Returns the total number of elements in the array.
size = a.size
print(size)
# Gives the total number of elements in the array.

# arr.dtype
# Definition: Returns the data type of the array elements.
dtype = a.dtype
print(dtype)
# Indicates the data type of the elements in the array.


# arr.resize(new_shape, refcheck=True, order='C')
# Definition: Resizes the array, changing its shape and possibly its data.
a = np.array([1, 2, 3])
print(a.resize(4, 2))
# Changes the shape of the array, potentially modifying the data.

# arr.flatten()
# Definition: Returns a copy of the array collapsed into one dimension.
flattened_array = a.flatten()
print(flattened_array)
# Creates a new one-dimensional array from the original array.

# arr.ravel()
# Definition: Returns a flattened array (may be a view).
raveled_array = a.ravel()
print(raveled_array)
# Creates a flattened array, possibly sharing memory with the original array.

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4.70774122e-310 0.00000000e+000 6.83609317e-310]
 [6.79038654e-313 2.14321575e-312 2.27053550e-312]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
2
9
float64
None
[1 2 3 0 0 0 0 0]
[1 2 3 0 0 0 0 0]


## Broadcasting

In [ ]:
import numpy as np

# Broadcasting
# Definition: A mechanism in NumPy that allows operations between arrays of different shapes.

# Example: Broadcasting with simple arrays
a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[1],[4],[5],[6]])  # Shape (3, 1)
print(a.shape,b.shape)
print(a,b)

# Perform element-wise addition
c = a + b
print("Broadcasting Example with simple arrays")
print(c)

# Example: Broadcasting with more complex arrays
a = np.array([[1, 2], [3, 4]])  # Shape (2, 2)
b = np.array([10, 20])  # Shape (2,)

# Perform element-wise multiplication
c = a * b
print("Broadcasting Example with complex arrays")
print(c)


# Broadcasting it aligns arrays of different shapes for arithmetic operations by stretching or repeating elements.

(3,) (4, 1)
[1 2 3] [[1]
 [4]
 [5]
 [6]]
Broadcasting Example with simple arrays
[[2 3 4]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
Broadcasting Example with complex arrays
[[10 40]
 [30 80]]


## Slicing

In [ ]:

# Create a sample array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic slicing: arr[start:stop:step]
# Definition: Extracts a portion of an array using start, stop, and step indices.
print("Basic slicing:")
slice_1 = arr[2:7:2]  # Elements from index 2 to 6 with a step of 2
print(slice_1)
#Creates a view of the original array, modifying the view affects the original array.

# Negative indexing
# Definition: Accesses elements from the end of the array.
print("Negative indexing:")
slice_2 = arr[-3:]  # Last three elements
print(slice_2)
#Negative indices count from the end of the array.

# Slicing multidimensional arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a specific row
print("Accessing a specific row:")
row_1 = arr_2d[1]
print(row_1)
# Access the second row

# Accessing a specific column
print("Accessing a specific column:")
col_2 = arr_2d[:, 1]
print(col_2)
# Access the second column

# Slicing a subarray
print("Slicing a subarray:")
sub_array = arr_2d[1:3, 1:3]
print(sub_array)
# Access a 2x2 subarray

Basic slicing:
[2 4 6]
Negative indexing:
[7 8 9]
Accessing a specific row:
[4 5 6]
Accessing a specific column:
[2 5 8]
Slicing a subarray:
[[5 6]
 [8 9]]


## View,Copy,Split

In [ ]:
import numpy as np

# Create a sample array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array copy
# Definition: Creates a new array with the same data as the original array.
copy_arr = arr.copy()
copy_arr[0] = 10
print("Array copy:")
print(arr)
print(copy_arr)
# Changes to the copy do not affect the original array.

# Array view
# Definition: Creates a new array object that shares the same data with the original array.
view_arr = arr.view()
view_arr[1] = 20
print("Array view:")
print(arr)
print(view_arr)
# Changes to the view affect the original array.

# Array splitting
# Definition: Splits an array into multiple sub-arrays.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Can split along different axes.

split_arr_rows = np.split(arr_2d, 3)
print("Splitting along rows:")
print(split_arr_rows)
# Splitting along the first axis (rows)

split_arr_cols = np.split(arr_2d, 3, axis=1)
print("Splitting along columns:")
print(split_arr_cols)
# Splitting along the second axis (columns)

Array copy:
[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]
Array view:
[ 0 20  2  3  4  5  6  7  8  9]
[ 0 20  2  3  4  5  6  7  8  9]
Splitting along rows:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Splitting along columns:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


### Random


np.random.rand:
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
np.random.randn:
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
np.random.randint:
[[14 10]
 [13  5]
 [14  7]]
np.random.choice:
[[1 9 8]
 [5 4 2]
 [0 7 3]]
np.random.shuffle:
[5 2 4 7 9 0 3 1 6 8]
np.random.permutation:
[9 7 0 2 5 6 3 1 4 8]
